export const EXERCISELIST = [
	"Dumbbell Bench Press",
	"Dumbbell Shoulder Press",
	"Dumbbell Rows",
	"Dumbbell Lunges",
	"Dumbbell Squats",
	"Dumbbell Deadlifts",
	"Dumbbell Bicep Curls",
	"Dumbbell Tricep Extensions",
	"Dumbbell Flyes",
	"Dumbbell Shrugs",
	"Dumbbell Step-Ups",
	"Dumbbell Hammer Curls",
	"Dumbbell Front Raises",
	"Dumbbell Lateral Raises",
	"Dumbbell Romanian Deadlifts",
	"Dumbbell Incline Press",
	"Dumbbell Pullovers",
	"Dumbbell Kickbacks",
	"Dumbbell Reverse Flyes",
	"Barbell Bench Press",
	"Barbell Shoulder Press",
	"Barbell Rows",
	"Barbell Lunges",
	"Barbell Squats",
	"Barbell Deadlifts",
	"Barbell Bicep Curls",
	"Barbell Tricep Extensions",
	"Barbell Bent-Over Rows",
	"Barbell Shrugs",
	"Barbell Upright Rows",
	"Barbell Skull Crushers",
	"Barbell Calf Raises",
	"Barbell Hip Thrusts",
	"Barbell Good Mornings",
	"Barbell Incline Press",
	"Barbell Pullovers",
	"Barbell Russian Twists",
	"Barbell Landmine Press",
	"Leg Extensions",
	"Leg Curls",
	"Standing Calf Raises",
	"Donkey Calf Raises",
	"Box Lunges",
	"Hexbar Deadlifts",
];
