import React, { useContext, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

//Contexts
import { WorkoutContext, initialWorkoutState } from "@contexts/WorkoutContext";

//Components
import SetWorkoutName from "@components/forms/SetWorkoutName";
import ExerciseList from "@components/app/ExerciseList";
import Button from "@components/Button";

export default function Workout() {
	const router = useRouter();

	const { workoutState, setWorkoutState } = useContext(WorkoutContext);
	const [completedWorkouts, setCompletedWorkouts] = useState([]);

	const uploadWorkout = (e: React.MouseEvent<HTMLButtonElement>) => {
		e.preventDefault();

		setCompletedWorkouts((prevState: any) => ({
			...prevState,
			workouts: [workoutState],
		}));

		setWorkoutState(initialWorkoutState);
		router.push("/");
	};

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Workout</h1>
			<SetWorkoutName />
			<ExerciseList />

			<Button onClick={uploadWorkout} fullw text={`finish`} />
		</>
	);
}
