import React, { useContext, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";

//Contexts
import { WorkoutContext, initialWorkoutState } from "@contexts/WorkoutContext";

//Components
import SetWorkoutName from "@components/forms/SetWorkoutName";
import ExerciseList from "@components/app/ExerciseList";
import FancyButton from "@components/buttons/FancyButton";
import WrapperContainer from "@components/app/WrapperContainer";
import Plus from "@components/icons/Plus";

export default function Workout() {
	const router = useRouter();

	const { workoutState, setWorkoutState } = useContext(WorkoutContext);
	const [completedWorkouts, setCompletedWorkouts] = useState([]);

	const uploadWorkout = (e: React.MouseEvent<HTMLButtonElement>) => {
		e.preventDefault();

		setCompletedWorkouts((prevState: any) => ({
			...prevState,
			workouts: [workoutState],
		}));

		setWorkoutState(initialWorkoutState);
		router.push("/");
	};

	const hasExercises = workoutState.exercises.length >= 1;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<WrapperContainer variant="overflow">
				{hasExercises ? <ExerciseList /> : <SetWorkoutName />}
			</WrapperContainer>

			<WrapperContainer variant="pinned">
				<Link href="/exercise">
					<FancyButton icon={<Plus />} text="add" />
				</Link>
				{/* {hasExercises && <Button onClick={uploadWorkout} fullw text="End workout" />} */}
			</WrapperContainer>
		</>
	);
}
